export const CATEGORIES = [
  { label: "Природа", value: "Nature" },
  { label: "Животные", value: "Animals" },
  { label: "Путешествия", value: "Travel" },
  { label: "Мода", value: "Fashion" },
  { label: "Технологии", value: "Technology" },
  { label: "Бизнес", value: "Business" },
  { label: "Еда", value: "Food" },
  { label: "Спорт", value: "Sports" },
  { label: "Люди", value: "People" },
  { label: "Архитектура", value: "Architecture" },
  { label: "Авто", value: "Cars" },
  { label: "Искусство", value: "Art" },
  { label: "Цветы", value: "Flowers" },
  { label: "Горы", value: "Mountains" },
  { label: "Пляж", value: "Beach" },
  { label: "Город", value: "City" },
  { label: "Небо", value: "Sky" },
  { label: "Ночь", value: "Night" },
  { label: "Закат", value: "Sunset" },
  { label: "Вода", value: "Water" },
  { label: "Игры", value: "Games" },
  { label: "Фитнес", value: "Fitness" },
  { label: "Интерьеры", value: "Interior" },
  { label: "Музыка", value: "Music" },
  { label: "Улица", value: "Street" },
  { label: "Деревня", value: "Village" },
  { label: "Портреты", value: "Portrait" },
  { label: "Любовь", value: "Love" },
  { label: "Море", value: "Sea" },
  { label: "Книги", value: "Books" },
  { label: "Зима", value: "Winter" },
  { label: "Лето", value: "Summer" },
  { label: "Осень", value: "Autumn" },
  { label: "Весна", value: "Spring" },
  { label: "Абстракция", value: "Abstract" },
  { label: "Домашние животные", value: "Home animals" },
  { label: "Образ жизни", value: "Lifestyle" },
  { label: "Лес", value: "Forest" },
  { label: "Пустыня", value: "Desert" },
  { label: "Подводная съемка", value: "Underwater" },
];
